module.exports = {
  purge: [
    "./src/components/album.js",
    "./src/components/albumDetail.js",
    "./src/components/albums.js",
    "./src/components/carousel.js",
    "./src/components/footer.js",
    "./src/components/homeContent.js",
    "./src/components/kid.js",
    "./src/components/kidDetail.js",
    "./src/components/kids.js",
    "./src/components/layout.js",
    "./src/components/newHeader.js",
    "./src/components/newHeaderMobile.js",
    "./src/components/newsletter.js",
    "./src/components/pageTitle.js",
    "./src/components/partnerCarousel.js",
    "./src/components/partners.js",
    "./src/components/seo.js",
    "./src/components/tourDate.js",
    "./src/components/tourDates.js",
    "./src/components/tourDetail.js",
    "./src/components/VipGalleryImage.js",
    "./src/components/vipGalleryListing.js",
    "./src/pages/dance-at-home/ep-1.js",
    "./src/pages/dance-at-home/ep-2.js",
    "./src/pages/dance-at-home/ep-3.js",
    "./src/pages/dance-at-home/ep-4.js",
    "./src/pages/dance-at-home/ep-5.js",
    "./src/pages/dance-at-home/ep-6.js",
    "./src/pages/vip-galleries/brantford.js",
    "./src/pages/vip-galleries/index.js",
    "./src/pages/vip-galleries/kingston.js",
    "./src/pages/vip-galleries/london.js",
    "./src/pages/vip-galleries/montreal.js",
    "./src/pages/vip-galleries/saultstemarie.js",
    "./src/pages/vip-galleries/sudbury.js",
    "./src/pages/vip-galleries/timmins.js",
    "./src/pages/404.js",
    "./src/pages/ambassador.js",
    "./src/pages/callback.js",
    "./src/pages/contact.js",
    "./src/pages/dance-at-home.js",
    "./src/pages/fun-at-home.js",
    "./src/pages/home.js",
    "./src/pages/index.js",
    "./src/pages/meet-the-mpk.js",
    "./src/pages/music.js",
    "./src/pages/personal-videos.js",
    "./src/pages/pop-star-programs.js",
    "./src/pages/privacy-policy.js",
    "./src/pages/shop.js",
    "./src/pages/terms-conditions.js",
    "./src/pages/thank-you.js",
    "./src/pages/tour.js",
    "./src/pages/videos.js",
    "./src/pages/vip-process.js",
    "./src/pages/walmartcanada.js",
  ],
  theme: {
    extend: {
      colors: {
        "main-pink": "#EE408E",
        "main-blue": "#00BAE7",
        "main-yellow": "#FFF200",
        "main-gray": "#4D4D4D",
        "main-black": "#221f1f",
        "highlight-pink": "#8d2168",
        "highlight-blue": "#226a73",
        "highlight-yellow": "#9d9334",
      },
    },
  },
  variants: {},
  plugins: [],
}
